local fzf_lua = require("fzf-lua")

vim.keymap.set("n", "<leader>ff", function()
	fzf_lua.files()
end, { desc = "FZF files" })
vim.keymap.set("n", "<leader>fh", function()
	fzf_lua.oldfiles()
end, { desc = "FZF history" })
vim.keymap.set("n", "<leader>fg", function()
	fzf_lua.live_grep()
end, { desc = "FZF grep" })
vim.keymap.set("n", "<leader>fqq", function()
	fzf_lua.quickfix()
end, { desc = "FZF quickfix" })
vim.keymap.set("n", "<leader>fqs", function()
	fzf_lua.quickfix_stack()
end, { desc = "FZF quickfix stack" })
vim.keymap.set("n", "<leader>fl", function()
	fzf_lua.loclist()
end, { desc = "FZF Location list" })
vim.keymap.set("n", "<leader>fi", function()
	fzf_lua.lines()
end, { desc = "FZF Lines" })
vim.keymap.set("n", "<leader>fs", function()
	fzf_lua.treesitter()
end, { desc = "FZF Treesitter" })
vim.keymap.set("n", "<leader>fb", function()
	fzf_lua.buffers()
end, { desc = "FZF Buffers" })
vim.keymap.set("n", "<leader>ft", function()
	fzf_lua.tabs()
end, { desc = "FZF Tabs" })
vim.keymap.set("n", "<leader>fu", function()
	fzf_lua.spell_suggest()
end, { desc = "FZF Spell suggest" })
vim.keymap.set("n", "<leader>fm", function()
	fzf_lua.marks()
end, { desc = "FZF Marks" })
vim.keymap.set("n", "<leader>fj", function()
	fzf_lua.jumps()
end, { desc = "FZF Jumps" })
vim.keymap.set("n", "<leader>fr", function()
	fzf_lua.registers()
end, { desc = "FZF Registers" })
vim.keymap.set("n", "<leader>fk", function()
	fzf_lua.keymaps()
end, { desc = "FZF Keymaps" })
vim.keymap.set("n", "<leader>fc", function()
	fzf_lua.lsp_code_actions()
end, { desc = "FZF Code Actions" })

-- Diagnostics
vim.keymap.set("n", "<leader>fdd", function()
	fzf_lua.lsp_definitions()
end, { desc = "FZF LSP Definitions" })
vim.keymap.set("n", "<leader>fdD", function()
	fzf_lua.lsp_declarations()
end, { desc = "FZF LSP Declarations" })
vim.keymap.set("n", "<leader>fdr", function()
	fzf_lua.lsp_references()
end, { desc = "FZF LSP References" })
vim.keymap.set("n", "<leader>fdi", function()
	fzf_lua.lsp_implementations()
end, { desc = "FZF LSP Implementations" })
vim.keymap.set("n", "<leader>fdb", function()
	fzf_lua.diagnostics_document()
end, { desc = "FZF Diagnostics Buffer" })
vim.keymap.set("n", "<leader>fdw", function()
	fzf_lua.diagnostics_workspace()
end, { desc = "FZF Diagnostics Workspace" })
