# Time
SPACESHIP_TIME_SHOW=true

# Prompt
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_ASYNC=false

# Async
SPACESHIP_ASYNC_SHOW_COUNT=false
SPACESHIP_ASYNC_SYMBOL=""

# Char
SPACESHIP_CHAR_SYMBOL="$"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_SYMBOL_ROOT="#"

